version: '3.8'

services:
  db:
    image: postgres:16
    container_name: time_manage_db
    restart: always
    environment:
      POSTGRES_DB: time_manage_db
      POSTGRES_USER: pupuser
      POSTGRES_PASSWORD: botinki
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: time-manage-max-bot
    restart: always
    depends_on:
      - db
    ports:
      - "25251:25251"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/time_manage_db
      SPRING_DATASOURCE_USERNAME: pupuser
      SPRING_DATASOURCE_PASSWORD: botinki
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: time-manage-max-front
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db_data:
