spring:
  datasource:
    url: jdbc:postgresql://db:5432/time_manage_db
    username: postgres
    password: botinki
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
				
		ai:
		    #These parameters apply when using the spring-ai-azure-openai-spring-boot-starter dependency:
		    azure:
		      openai:
		        api-key: "the-api-key"
		        endpoint: "https://the-url/"
		        chat:
		          options:
		             deployment-name: "gpt-4o"
server:
  port: 25251